def quiz_analizer(answers: str) -> str:
    chelovek_chelovek = []
    chelovek_technika = []
    chelovek_priroda = []
    chelovek_izo = []
    chelovek_zs = []
    a = list(answers)
    # s = list(a)
    # s = sum([list(i) for i in a], [])
    # print(s)
    # print(s[4])
    print(a)
    if a[0] == '+': chelovek_chelovek.append(1)
    if a[3] == '+': chelovek_priroda.append(1)
    if a[4] == '+': chelovek_zs.append(1)
    if a[2] == '+': chelovek_izo.append(1)
    if a[1] == '+': chelovek_technika.append(1)
    if a[5] == '+': chelovek_chelovek.append(1)
    if a[6] == '+': chelovek_priroda.append(1)
    if a[7] == '+': chelovek_zs.append(1)
    if a[11] == '+': chelovek_izo.append(1)
    if a[12] == '+': chelovek_technika.append(1)
    if a[19] == '+': chelovek_chelovek.append(1)
    if a[10] == '+': chelovek_priroda.append(1)
    if a[21] == '+': chelovek_zs.append(1)
    if a[23] == '+': chelovek_izo.append(1)
    if a[20] == '+': chelovek_technika.append(1)
    if a[26] == '+': chelovek_chelovek.append(1)
    if a[27] == '+': chelovek_priroda.append(1)
    if a[28] == '+': chelovek_zs.append(1)
    if a[29] == '+': chelovek_izo.append(1)
    if a[25] == '+': chelovek_technika.append(1)
    if a[14] == '+': chelovek_chelovek.append(2)
    if a[24] == '+': chelovek_priroda.append(2)
    if a[18] == '+': chelovek_zs.append(2)
    if a[16] == '+': chelovek_izo.append(2)
    if a[15] == '+': chelovek_technika.append(2)
    if a[22] == '+': chelovek_chelovek.append(2)
    if a[17] == '+': chelovek_priroda.append(2)
    if a[13] == '+': chelovek_zs.append(2)
    if a[9] == '+': chelovek_izo.append(2)
    if a[8] == '+': chelovek_technika.append(2)
    b1 = sum(chelovek_zs)
    b2 = sum(chelovek_technika)
    b3 = sum(chelovek_priroda)
    b4 = sum(chelovek_chelovek)
    b5 = sum(chelovek_izo)
    m = max(b1, b2, b3, b4, b5)
    v=[]
    if m==b1:v.append(1)
    if m==b2:v.append(1)
    if m==b3:v.append(1)
    if m==b4:v.append(1)
    if m==b5:v.append(1)
    if len(v) >= 2:
        print('Вам подходит несколько направлений, выбирите одно из них:')
        if m==b1:print('человек знакаовая система')
        if m==b2:print('человек техника')
        if m==b3:print('человек природа')
        if m==b4:print('человек человек')
        if m==b5:print('человек изо')
    else:
        if m==b1:print('Ты человек знакаовая система')
        elif m==b2:print('Ты человек техника')
        elif m==b3:print('Ты человек природа')
        elif m==b4:print('Ты человек человек')
        elif m==b5:print('Ты человек изо')
    a.clear()
    return 'Вы прошли тест'